---
- name: install apache2 on ubuntu server
  hosts: 10.0.0.192
  become: yes
  become_user: akhil
  become_method: sudo
  tasks:
  - name: install apache2
    apt: 
      name: apache2
      state: present
    
 
  - name: start apache2
    service: 
      name: apache2
      state: started
