---
- name: install apache2 on ubuntu server
  hosts: 10.0.0.192
  tasks:
  - name: install apache2
    apt: 
      name: apache2
      state: present
    become: true
    become_user: akhil
    become_method: sudo
 
  - name: start apache2
    service: 
      name: apache2
      state: started
